---
apiVersion: v1
data:
  policy.csv: |
    g, akuityio:engineering, role:admin
    g, akuityio:demo, role:admin
    g, mike, role:admin
  policy.default: role:readonly
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: argocd-rbac-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-rbac-cm
