name: Reconcile
on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
jobs:
  diff:
    name: Reconcile Akuity Platform Settings
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install Akuity CLI
      run: |
        curl -sSL -o /usr/local/bin/akuity "https://dl.akuity.io/akuity-cli/$(curl -sL https://dl.akuity.io/akuity-cli/stable.txt)/linux/amd64/akuity"
        chmod +x /usr/local/bin/akuity
        akuity version
        akuity config set --organization-name=demo
    - name: Reconcile
      env:
        AKUITY_API_KEY_ID: ${{ secrets.AKUITY_API_KEY_ID }}
        AKUITY_API_KEY_SECRET: ${{ secrets.AKUITY_API_KEY_SECRET }}
        PR_NUMBER: ${{ github.event.number }}
        GH_TOKEN: ${{ github.token }}
      run: |
        ls argocd | xargs -I {} ./hack/reconcile.sh {} argocd/{}